export declare const TABLE_OPT_VALUES: string[];
export declare const FEILD_TEMPLATE: string;
export declare const WHERE_TERM_API: {
    equal: string;
    notEqual: string;
    in: string;
    notIn: string;
    more: string;
    less: string;
    moreEqual: string;
    lessEqual: string;
    like: string;
    notLike: string;
    between: string;
    notBetween: string;
    orEqual: string;
    orNotEqual: string;
    orIn: string;
    orNotIn: string;
    orMore: string;
    orLess: string;
    orMoreEqual: string;
    orLessEqual: string;
    orLike: string;
    orNotLike: string;
    orBetween: string;
    orNotBetween: string;
};
export declare const HAVING_TERM_API: {
    equal: string;
    notEqual: string;
    in: string;
    notIn: string;
    more: string;
    less: string;
    moreEqual: string;
    lessEqual: string;
    like: string;
    notLike: string;
    between: string;
    notBetween: string;
    orEqual: string;
    orNotEqual: string;
    orIn: string;
    orNotIn: string;
    orMore: string;
    orLess: string;
    orMoreEqual: string;
    orLessEqual: string;
    orLike: string;
    orNotLike: string;
    orBetween: string;
    orNotBetween: string;
};
